# Deploy mediahub-ws
- name: Create mediahub-ws directory
  file:
    path: /opt/mediahubws
    state: directory

- name: Create mediahub-ws/bin directory
  file:
    path: /opt/mediahubws/bin
    state: directory

- name: Create mediahub-ws/lib directory
  file:
    path: /opt/mediahubws/lib
    state: directory

- name: Create mediahub-ws/release directory
  file:
    path: /opt/mediahubws/release
    state: directory

- name: Copy the mediahubws-0.0.1-SNAPSHOT.jar file to the mediahub-ws/release directory
  copy:
    src: mediahubws-0.0.1-SNAPSHOT.jar
    dest: /opt/mediahubws/release/mediahubws-0.0.1-SNAPSHOT.jar
    owner: root
    group: root
    mode: 0755

- name: Create a symlink to the mediahubws jar file
  file:
    src: /opt/mediahubws/release/mediahubws-0.0.1-SNAPSHOT.jar
    dest: /opt/mediahubws/bin/mediahubws
    state: link
    owner: root
    group: root

- name: Copy the mediahubws service file to the /etc/init.d/ directory 
  copy:
    src: mediahubws
    dest: /etc/init.d/mediahubws
    owner: root
    group: root
    mode: 0755

- name: Start mediahub-ws
  service:
    name: mediahubws
    enabled: yes
    state: started

- name: Test the mediahub-ws API (health check)
  uri:
    url: "http://{{ ansible_host }}:8080/api/v1/isAlive"
    method: GET
    return_content: true
  register: health_check

- name: Print the health check result
  debug:
    var: health_check