ffmpeg:
  hosts:
    mediahub-05:
      ansible_host: 192.168.1.105 #target host IP address
      ansible_connection: local #instead of getting SSH connection to the tagert host, the commands will be excuted locally on AWX
      ansible_python_interpreter: '{{ ansible_playbook_python }}' #target host python interpreter
      ansible_user: root #target host user
      ansible_os_family: Debian
      ansible_distribution: Ubuntu
    mediahub-06:
      ansible_host: 192.168.1.106
      ansible_connection: local
      ansible_python_interpreter: '{{ ansible_playbook_python }}'