ffmpeg:
  hosts:
    mediahub-05:
      ansible_host: 192.168.1.105
      ansible_connection: local
      ansible_python_interpreter: '{{ ansible_playbook_python }}'
    mediahub-06:
      ansible_host: 192.168.1.106
      ansible_connection: local
      ansible_python_interpreter: '{{ ansible_playbook_python }}'