---
- name: Installer ffmpeg sur Ubuntu
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Installer ffmpeg
      apt:
        name: ffmpeg
        state: present
        update_cache: true
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
