---
- hosts: mediahub
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Install package ffmpeg
      apt:
        name: ffmpeg
        state: present
        update_cache: yes 
