---
- name: Install FFmpeg
  hosts: mediahub
  become: true
  tasks:
    - name: Update Ubuntu packages
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install package ffmpeg
      ansible.builtin.apt:
        name: ffmpeg
        state: present
