- name: Tester l'environnement distant
  hosts: all
  become: true
  tasks:
    - name: Afficher le PATH du shell root
      shell: "echo $PATH"
      register: result

    - debug:
        var: result.stdout
