# This is the main playbook for deploying Mediahub and its dependencies.
# It includes the roles for ffmpeg, java, mariadb, mediahub, shaka-packager, and tsduck.
---
- name: Deploy Mediahub
  hosts: all
  gather_facts: false
  roles:
    - ffmpeg
    - java
    - mariadb # Mediahub DB + configure user
    - mediahub # install mediahub-ws+ mediahub-admin
#    - shaka-packager
#    - tsduck