---
# This playbook installs ffmpeg on the mediahub server.
- hosts: mediahub
  become: true
  tasks:
    - name: Install package ffmpeg
      apt:
        name: ffmpeg
        state: present
        update_cache: yes 
