---
- name: Check OS type
  shell: cat /etc/os-release | grep ID= | cut -d= -f2 | tr -d '"'
  register: os_type
  changed_when: false

- name: Debug OS type
  debug:
    msg: "OS Type: {{ os_type.stdout }}"

- name: Installation of system dependencies (Debian)
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - curl
    - net-tools
    - plocate
    - git
  when: "'debian' in os_type.stdout or 'ubuntu' in os_type.stdout"

- name: Installation of system dependencies (RedHat)
  dnf:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - curl
    - net-tools
    - mlocate
    - git
  when: "'centos' in os_type.stdout or 'rhel' in os_type.stdout"

- name: Installation of ffmpeg (Debian)
  apt:
    name: ffmpeg
    state: present
    update_cache: no
  register: ffmpeg_install
  when: "'debian' in os_type.stdout or 'ubuntu' in os_type.stdout"

- name: Installation of ffmpeg (RedHat)
  dnf:
    name: ffmpeg
    state: present
    update_cache: no
  register: ffmpeg_install
  when: "'centos' in os_type.stdout or 'rhel' in os_type.stdout"

- name: Check ffmpeg version
  command: ffmpeg -version
  register: ffmpeg_version
  changed_when: false
  failed_when: ffmpeg_install is failed

- name: Display ffmpeg version
  debug:
    msg: "{{ ffmpeg_version.stdout_lines[0] }}"
  when: ffmpeg_version is defined