---
- name: Set OS family fact
  set_fact:
    ansible_os_family: "{{ ansible_facts.os_family }}"
    ansible_distribution: "{{ ansible_facts.distribution }}"
    ansible_distribution_version: "{{ ansible_facts.distribution_version }}"

- name: Debug OS family
  debug:
    msg: "OS Family: {{ ansible_os_family }}, Distribution: {{ ansible_distribution }}, Version: {{ ansible_distribution_version }}"

- name: Install python3-apt (Debian)
  shell: /usr/bin/apt-get update && /usr/bin/apt-get install -y python3-apt
  become: yes
  args:
    executable: /bin/bash
  when: ansible_os_family == "Debian"

- name: Install python3-apt (RedHat)
  dnf:
    name: python3-apt
    state: present
  become: yes
  when: ansible_os_family == "RedHat"

- name: Update apt cache (Debian)
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Update dnf cache (RedHat)
  dnf:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "RedHat"

- name: Installation of system dependencies (Debian)
  apt:
    name: "{{ item }}"
    state: present
    update_cache: no
  loop:
    - curl
    - net-tools
    - plocate
    - git
  when: ansible_os_family == "Debian"

- name: Installation of system dependencies (RedHat)
  dnf:
    name: "{{ item }}"
    state: present
    update_cache: no
  loop:
    - curl
    - net-tools
    - mlocate
    - git
  when: ansible_os_family == "RedHat"

- name: Installation of ffmpeg (Debian)
  apt:
    name: ffmpeg
    state: present
    update_cache: no
  register: ffmpeg_install
  when: ansible_os_family == "Debian"

- name: Installation of ffmpeg (RedHat)
  dnf:
    name: ffmpeg
    state: present
    update_cache: no
  register: ffmpeg_install
  when: ansible_os_family == "RedHat"

- name: Check ffmpeg version
  command: ffmpeg -version
  register: ffmpeg_version
  changed_when: false
  failed_when: ffmpeg_install is failed

- name: Display ffmpeg version
  debug:
    msg: "{{ ffmpeg_version.stdout_lines[0] }}"
  when: ffmpeg_version is defined