---
- name: Set OS family fact
  set_fact:
    ansible_os_family: "{{ ansible_facts.os_family }}"
    ansible_distribution: "{{ ansible_facts.distribution }}"
    ansible_distribution_version: "{{ ansible_facts.distribution_version }}"

- name: Debug OS family
  debug:
    msg: "OS Family: {{ ansible_os_family }}, Distribution: {{ ansible_distribution }}, Version: {{ ansible_distribution_version }}"

- name: Installation of system dependencies (Debian)
  apt:
    name: "{{ item }}"
    state: present
    update_cache: no
  loop:
    - net-tools
    - git