---
- name: Set OS family fact
  set_fact:
    ansible_os_family: "Debian"
    ansible_distribution: "Ubuntu"
    ansible_distribution_version: "22.04"

- name: Debug OS family
  debug:
    msg: "OS Family: {{ ansible_os_family }}, Distribution: {{ ansible_distribution }}, Version: {{ ansible_distribution_version }}"

- name: Installation of system dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - net-tools
    - plocate
    - git
  when: ansible_os_family == "Debian"

- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Installation of ffmpeg
  package:
    name: ffmpeg
    state: present
  register: ffmpeg_install

- name: Check ffmpeg version
  command: ffmpeg -version
  register: ffmpeg_version
  changed_when: false
  failed_when: ffmpeg_install is failed

- name: Display ffmpeg version
  debug:
    msg: "{{ ffmpeg_version.stdout_lines[0] }}"
  when: ffmpeg_version is defined 