---
# This playbook installs and configures a mariadb server on the mediahub server.
- name: MariaDB Server Installation
  apt:
      name: mariadb-server
      state: present
 
- name: Ensure MariaDB Server is at the latest version
  apt:
      name: mariadb-server
      state: latest
 
- name: Ensure that MariaDB Server is started
  service:
      name: mariadb
      state: started

- name: copy mysql_secure_installation.sh to /root
  copy:
    src: mysql_secure_installation.sh
    dest: /home/ansible/mysql_secure_installation.sh
    mode: '0755'

- name: Launch mysql_secure_installation
  shell: sudo ./mysql_secure_installation.sh

- name: Create the ansible_user
  community.mysql.mysql_user:
    name: ansible_user
    password: "{{ ansible_user_password }}"
    login_user: root
    state: present

- name: Grant all privileges to the mediahub user
  community.mysql.mysql_user:
    name: ansible_user
    priv: '*.*:ALL'
    login_user: root
    state: present


- name: Flush privileges
  community.mysql.mysql_user:
    name: ansible_user
    flush_privileges: true
    login_user: root
    state: present

 
- name: Create Mediahub DB
  community.mysql.mysql_db:
      name: media_hub
      login_user: ansible_user
      login_password: "{{ ansible_user_password }}"
      state: present

